### ISSUE TITLE
How can i use Integer min max in .commodore file

### ISSUE THREAD

**Issue by B4TT3RY** [lucko/commodore#10]
How can i use Integer min max in .commodore file
`amount brigadier:integer 1 100;` isn't working.
error: `Node definition not ended with semicolon`

**Comment by B4TT3RY** [comment]
Solved

**Comment by nicegamer7** [comment]
Can you please explain how?

**Comment by B4TT3RY** [comment]
> Can you please explain how?

update 1.5 to 1.7
