### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by jpenilla** [lucko/commodore#25]
https://github.com/Incendo/cloud/commit/9dde0775435984fc512d7f551cc2927e32d198f9 This commit may be useful for updating to 1.19, not sure if I will have time to PR it myself

**Comment by lucko** [comment]
Thanks - think my plan from now on is to minimise reflection and just act as a wrapper around Paper's Mojang-API.

See 98f39247bf37ae5e754589a60bfd0d6f5c35533d for more info
