### ISSUE TITLE
1.19.1 support

### ISSUE THREAD

**Issue by henkelmax** [lucko/commodore#27]
Version `2.0` seems to have some issues with 1.19.1. The completion itself works fine, but when trying to execute the command, the game doesn't seem to recognize the command: `Unknown or incomplete command, see below for error`.
Removing the commodore registration fixes the issue.

**Comment by henkelmax** [comment]
I did a little further investigation and it seems that the dummy command actually gets executed:

https://github.com/lucko/commodore/blob/25c9459494ef58be5d58c1e61bd2b044278e1aaf/src/main/java/me/lucko/commodore/CommodoreImpl.java#L139

If I remove the `UnsupportedOperationException` it actually executes that command but still does not propagate the command to bukkits command executor.

**Comment by lucko** [comment]
Fixed in commodore 2.1 / 98f39247bf37ae5e754589a60bfd0d6f5c35533d
