### ISSUE TITLE
1.19.1 Not working for client side of servers(PaperMC)

### ISSUE THREAD

**Issue by JS427** [lucko/commodore#28]
Basicly I tried using LuckPerms on my 1.19.1 PaperMC server but, it just keep saying "An unexpected error occured trying to execute that commmand". So I tried it on the console it executed the command PLEASE FIX THIS SOON...

**Comment by lucko** [comment]
Fixed in commodore 2.1 / 98f39247bf37ae5e754589a60bfd0d6f5c35533d
