### ISSUE TITLE
Cannot find  CommodoreFileFormat

### ISSUE THREAD

**Issue by ilgrandeanonimo** [lucko/commodore#34]
Cannot resolve symbol 'CommodoreFileFormat'
how can i fix that?

**Comment by Byte-Developments** [comment]
Hi! You can set your parameters to "shadowJar". This will include the libraries inside your plugins JAR file. Thank you :)

**Comment by ilgrandeanonimo** [comment]
Already Fixed, Forgot to Close

**Comment by Byte-Developments** [comment]
Haha, no problem.

**Comment by ilgrandeanonimo** [comment]
I don't now why it works but is fine
