### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TsvetozarDEV** [lucko/commodore#6]
Hi, I've tried everything but not worked for me :(
Even creating a new project and copying literally everything you say on the README didn't work.
And do Luckperms have commodore, because it didn't show for me as you say in commodore resource post.

**Comment by Andre601** [comment]
![image](https://user-images.githubusercontent.com/11576465/65606298-e91df600-dfaa-11e9-9b6a-04c28467fc33.png)

**Comment by TsvetozarDEV** [comment]
There's been almost a year since last comment and I just see that it isn't closed. Closing it.
